
artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: tarin.tsv
  TEST_DATA: test.tsv

local_data_file_path: C:/Users/Hp/Downloads/============--ML Project With Rohan--=/stack-overflow-project sk/data.xml

split_ratio: 0.3

